### ISSUE TITLE
cdc-service stops sending events to kafka after temporal loss of connection to mysql

### ISSUE THREAD

**Issue by KarolisL** [eventuate-local/eventuate-local#10]
I've ran into an issue when running cdc-service on kubernetes cluster: I've restarted mysql, so connection dropped and then became available after a while.

After restarting CDC, the events were published to kafka and received by event handlers.

Steps to reproduce:
* Stop mysql
* Wait about 10 sec
* Start mysql

Expected behaviour:
New events gets published

Actual behaviour:
Events doesn't get published

Workaround:
Restart `cdc-service` after mysql becomes available

If this is not easily solvable, a simple HTTP endpoint for quering connection health would help -- kubernetes would restart CDC when connection is dropped.

Log: 
[cdc-log-gh.txt](https://github.com/eventuate-local/eventuate-local/files/1097628/cdc-log-gh.txt)

**Comment by cer** [comment]
Thanks for reporting this.
Your suggestion of exposing the health of the connector is probably the best way to go.

**Comment by cer** [comment]
This [commit](https://github.com/eventuate-local/eventuate-local/commit/fda7dd1ff10e7d33dd31d855f4657912cc8efa16) should address that problem.

It adds a HealthIndicator so GET /health will report on the status but more importantly it loops attempting to reconnect to MySQL (and Kafka).

See the [test scenario](https://github.com/eventuate-local/eventuate-local/blob/master/scripts/build-and-test-all-cdc.sh).

I've released the 0.12.6 libraries and the Docker images are in the build queue.

**Comment by cer** [comment]
@KarolisL Did this take care of the issue?

**Comment by KarolisL** [comment]
Yes, looks like it helped. Thanks!
