### ISSUE TITLE
Eventuate Tram My SQL CDC Service : connection to mysql binlog failed

### ISSUE THREAD

**Issue by satijasattu** [eventuate-local/eventuate-local#124]
HI,
I am trying to configure Eventuate CDC service with MySQL using docker containers and I am getting following error . Below is the docker-compose fie 

zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.17.0.RELEASE
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

kafka:
  image: eventuateio/eventuateio-local-kafka:0.17.0.RELEASE
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

mysql:
  image: eventuateio/eventuate-tram-mysql:0.6.0.RELEASE
  ports:
    - 3307:3307
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root

adminer:
    image: adminer:4.3.1-standalone
    ports:
        - 9080:8080

tramcdcservice:
  image: eventuateio/eventuate-tram-cdc-mysql-service:0.6.0.RELEASE
  ports:
    - "8099:8080"
  links:
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/salesorder?autoReconnect=true&useSSL=false
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: root
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: root
    EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 67890
    EVENTUATELOCAL_CDC_SOURCE_TABLE_NAME: message

Following are the error logs :

kafka_1_f059fedf82ea | [2019-07-01 13:05:34,458] INFO [GroupCoordinator 0]: Preparing to restabilize group 221926ad-e08a-47ad-b81a-c72f71c93dfd with old generation 1 (kafka.coordinator.GroupCoordinator)
kafka_1_f059fedf82ea | [2019-07-01 13:05:34,459] INFO [GroupCoordinator 0]: Group 221926ad-e08a-47ad-b81a-c72f71c93dfd generation 1 is dead and removed (kafka.coordinator.GroupCoordinator)
mysql_1_9bc278c31087 | Initializing database
mysql_1_9bc278c31087 | 2019-07-01T13:05:59.494926Z 0 [Warning] InnoDB: New log files created, LSN=45790
mysql_1_9bc278c31087 | 2019-07-01T13:05:59.588266Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
tramcdcservice_1_f0e1cfb6bfd7 | 13:05:59.683 [Curator-LeaderSelector-0] INFO  i.e.l.m.binlog.MySqlBinaryLogClient - trying to connect to mysql binlog
tramcdcservice_1_f0e1cfb6bfd7 | 13:05:59.684 [Curator-LeaderSelector-0] ERROR i.e.l.m.binlog.MySqlBinaryLogClient - connection to mysql binlog failed
mysql_1_9bc278c31087 | 2019-07-01T13:05:59.696144Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: f8a44dd8-9c00-11e9-a9f1-0242ac110008.
mysql_1_9bc278c31087 | 2019-07-01T13:05:59.701915Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
mysql_1_9bc278c31087 | 2019-07-01T13:05:59.709014Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
mysql_1_9bc278c31087 | 2019-07-01T13:06:02.094359Z 1 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | 2019-07-01T13:06:02.094418Z 1 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | 2019-07-01T13:06:02.094437Z 1 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | 2019-07-01T13:06:02.094448Z 1 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | 2019-07-01T13:06:02.094478Z 1 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | Database initialized
mysql_1_9bc278c31087 | MySQL init process in progress...
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:04.685 [Curator-LeaderSelector-0] INFO  i.e.l.m.binlog.MySqlBinaryLogClient - trying to connect to mysql binlog
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:04.774 [Curator-LeaderSelector-0] ERROR i.e.l.m.binlog.MySqlBinaryLogClient - connection to mysql binlog failed
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.801847Z 0 [Note] mysqld (mysqld 5.7.13-log) starting as process 51 ...
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.829264Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.829317Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.829323Z 0 [Note] InnoDB: Uses event mutexes
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.829326Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.829329Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.829331Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.829631Z 0 [Note] InnoDB: Number of pools: 1
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.829753Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.831046Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.839858Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.841856Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.863525Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.887022Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.887082Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.960993Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.962326Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.962379Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql_1_9bc278c31087 | 2019-07-01T13:06:04.962692Z 0 [Note] InnoDB: Waiting for purge to start
mysql_1_9bc278c31087 | 2019-07-01T13:06:05.012867Z 0 [Note] InnoDB: 5.7.13 started; log sequence number 2525487
mysql_1_9bc278c31087 | 2019-07-01T13:06:05.014053Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1_9bc278c31087 | 2019-07-01T13:06:05.014120Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1_9bc278c31087 | 2019-07-01T13:06:05.042557Z 0 [Note] InnoDB: Buffer pool(s) load completed at 190701 13:06:05
mysql_1_9bc278c31087 | 2019-07-01T13:06:05.061624Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
mysql_1_9bc278c31087 | 2019-07-01T13:06:05.072740Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | 2019-07-01T13:06:05.072854Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | 2019-07-01T13:06:05.073929Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | 2019-07-01T13:06:05.073971Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | 2019-07-01T13:06:05.100502Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | 2019-07-01T13:06:05.152176Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1_9bc278c31087 | 2019-07-01T13:06:05.152533Z 0 [Note] mysqld: ready for connections.
mysql_1_9bc278c31087 | Version: '5.7.13-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
mysql_1_9bc278c31087 | Warning: Unable to load '/usr/share/zoneinfo/Factory' as time zone. Skipping it.
mysql_1_9bc278c31087 | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql_1_9bc278c31087 | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql_1_9bc278c31087 | Warning: Unable to load '/usr/share/zoneinfo/posix/Factory' as time zone. Skipping it.
mysql_1_9bc278c31087 | Warning: Unable to load '/usr/share/zoneinfo/right/Factory' as time zone. Skipping it.
mysql_1_9bc278c31087 | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql_1_9bc278c31087 | 2019-07-01T13:06:08.436256Z 4 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | 2019-07-01T13:06:08.436309Z 4 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | 2019-07-01T13:06:08.436347Z 4 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1_9bc278c31087 | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql_1_9bc278c31087 | ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:09.774 [Curator-LeaderSelector-0] INFO  i.e.l.m.binlog.MySqlBinaryLogClient - trying to connect to mysql binlog
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:09.777 [Curator-LeaderSelector-0] ERROR i.e.l.m.binlog.MySqlBinaryLogClient - connection to mysql binlog failed
kafka_mysql_1_9bc278c31087 exited with code 1
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:14.777 [Curator-LeaderSelector-0] INFO  i.e.l.m.binlog.MySqlBinaryLogClient - trying to connect to mysql binlog
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:14.817 [Curator-LeaderSelector-0] ERROR i.e.l.m.binlog.MySqlBinaryLogClient - connection to mysql binlog failed
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:19.817 [Curator-LeaderSelector-0] INFO  i.e.l.m.binlog.MySqlBinaryLogClient - trying to connect to mysql binlog
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:19.819 [Curator-LeaderSelector-0] ERROR i.e.l.m.binlog.MySqlBinaryLogClient - connection to mysql binlog failed
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:24.820 [Curator-LeaderSelector-0] INFO  i.e.l.m.binlog.MySqlBinaryLogClient - trying to connect to mysql binlog
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:24.851 [Curator-LeaderSelector-0] ERROR i.e.l.m.binlog.MySqlBinaryLogClient - connection to mysql binlog failed
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:29.852 [Curator-LeaderSelector-0] INFO  i.e.l.m.binlog.MySqlBinaryLogClient - trying to connect to mysql binlog
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:29.854 [Curator-LeaderSelector-0] ERROR i.e.l.m.binlog.MySqlBinaryLogClient - connection to mysql binlog failed
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:34.855 [Curator-LeaderSelector-0] INFO  i.e.l.m.binlog.MySqlBinaryLogClient - trying to connect to mysql binlog
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:34.906 [Curator-LeaderSelector-0] ERROR i.e.l.m.binlog.MySqlBinaryLogClient - connection to mysql binlog failed
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:39.907 [Curator-LeaderSelector-0] INFO  i.e.l.m.binlog.MySqlBinaryLogClient - trying to connect to mysql binlog
tramcdcservice_1_f0e1cfb6bfd7 | 13:06:39.908 [Curator-LeaderSelector-0] ERROR i.e.l.m.binlog.MySqlBinaryLogClient - connection to mysql binlog failed

**Comment by cer** [comment]
What's `mysql-standalone`?
That's the hostname in the jdbc url.
It's not the name of a container.

The CDC container should be linked to MySQL and use that as the hostname.

**Comment by satijasattu** [comment]
HI Cer , Thank you for your response .Mysql-standalone is the name the docker container which I created and it is having mysql server and database schema salesorder . I want the CDC service to read the binlog of message table present in salesorder database hence I mentioned it in the Data source URL .

It will be really great if you could please elaborate  "The CDC container should be linked to MySQL and use that as the hostname " in little detail.

**Comment by satijasattu** [comment]
HI,

This is how I created the MySql Container 

docker run --name mysql-standalone -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=inventory -e MYSQL_USER=sattu -e MYSQL_PASSWORD=root -d mysql:5.6

**Comment by satijasattu** [comment]
HI Cer, 

Yes , you were right the  , CDC container was not linked with mySQL, Now I am able to read the binlogs .
Thanks for the support

Regards
Rahul

**Comment by cer** [comment]
Glad you figured it out.
