### ISSUE TITLE
[question/request] Support of PostgreSQL - any plans?

### ISSUE THREAD

**Issue by archenroot** [eventuate-local/eventuate-local#17]
Hi,

would you support PostgreSQL in future or do you have this already in your roadmap?

Thanks.

**Comment by eventuate-docker-images** [comment]
Yes. The code is in github. We are working on an example application. See docker-*postgres.yml files

**Comment by cer** [comment]
@archenroot 
Please see https://github.com/eventuate-examples/eventuate-examples-java-spring-todo-list
It now supports Postgres.

This still needs to be documented, etc.
