### ISSUE TITLE
[question] Support of MongoDB as Event Store

### ISSUE THREAD

**Issue by archenroot** [eventuate-local/eventuate-local#22]
Hi, I put it here as I am interested in on-premise only version.

Is there any blockade for MongoDB to be supported for Event Store? You extended PostgreSQL support (thank you). As this was my preferred solution, the more I consider MongoDB as local instance for services to support Aggregates materialization, the more I think of using MongoDB for Event Store as well.

I could look at this myself, just with some hints about what would need to be changed, I am not asking for doing this.

Thanks for any info.

**Comment by eventuateio** [comment]
I believe it is very doable.

One simple strategy would be to use a MongoDB document-per-aggregate. Each document stores the events for an aggregate. Alternatively, an application could use a document-per-event.

The MongoDB version of CDC service can read from the MongoDB oplog.

**Comment by archenroot** [comment]
I am actually now looking for adoption of eventuate fork in form of light eventuate 4j, so will se which one finally win and I will focus on implementation myself.

thanks for info.
