### ISSUE TITLE
cdc-service fails when there exists database with `-` in their name

### ISSUE THREAD

**Issue by KarolisL** [eventuate-local/eventuate-local#7]
The same as #6. I have described the problem wrongly there, it's database rather than table.

It is fixed in 0.3.6 of debezium: https://github.com/debezium/debezium/blob/v0.3.6/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java#L260

P.S. I was not able to make current tests pass on my local machine, so I'm not doing a PR. Docs on how to properly run tests would be helpful. :-)

**Comment by cer** [comment]
Thanks for clarifying the problem and suggesting a fix.
I'll make a new release later today.

You can run the tests using ./scripts/build-and-test-all.sh - it sets some environment variables, starts containers etc.

**Comment by cer** [comment]
@KarolisL Released the 0.12.3.RELEASE libraries and the 0.12.3 images.

**Comment by KarolisL** [comment]
Hello,

I see that debezium version is the same: https://github.com/eventuate-local/eventuate-local/blob/master/gradle.properties#L13

Is it really fixed?

**Comment by cer** [comment]
Oops. Sorry about that.

**Comment by cer** [comment]
@KarolisL Released the 0.12.4.RELEASE libraries and the 0.12.4 images.
