### ISSUE TITLE
Is CI needed?

### ISSUE THREAD

**Issue by KarolisL** [eventuate-local/eventuate-local#9]
Would it make sense to have a CI running tests of PRs/master? If so, I've got somewhat-working solution using CircleCI at https://github.com/KarolisL/eventuate-local/blob/circleci/circle.yml

Example: https://circleci.com/gh/KarolisL/eventuate-local/11

I am not "related" to CircleCI, just found it the easiest. They provide free CI solution for open source projects. Another option known to me is TravisCI.org. I could set that up also.

**Comment by cer** [comment]
Thanks for investigating this. I like the idea of setting up a public CI server.

One challenge until now was that some kinds of tests weren't automated. Part of the work I've done over the past week is to improve the tests.

Specifically see https://github.com/eventuate-local/eventuate-local/blob/master/scripts/build-and-test-all-cdc.sh - this now tests the MySQL disconnect scenario.

So there two test scripts to run:
1. ./scripts/build-and-test-all.sh
2. ./scripts/build-and-test-all-cdc.sh

**Comment by KarolisL** [comment]
Since you've merged the PR, I'll close the issue. Reopen if you need any help regarding CI.

**Comment by eventuateio** [comment]
Thanks. CircleCI is up and running although there is probably more
configuration to.

build-and-test-all.sh works fine. build-and-test-all-cdc.sh is failing -
haven't had a chance to investigate.
